name: Example Run

on:
  merge_group:
  pull_request:
  # also run when pushed to main to update reference screenshots
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  run-examples-linux-vulkan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      # At some point this may be merged into `install-linux-deps`, but for now it is its own step.
      - name: Install additional Linux dependencies for Vulkan
        run: |
          sudo add-apt-repository ppa:kisak/turtle -y
          sudo apt-get install --no-install-recommends libxkbcommon-x11-0 xvfb libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-run-examples-${{ hashFiles('**/Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Run examples
        run: |
          for example in .github/example-run/*.ron; do
            example_name=`basename $example .ron`
            echo -n $example_name > last_example_run
            echo "running $example_name - "`date`
            time TRACE_CHROME=trace-$example_name.json CI_TESTING_CONFIG=$example xvfb-run cargo run --example $example_name --features "bevy_ci_testing,trace,trace_chrome"
            sleep 10
            if [ `find ./ -maxdepth 1 -name 'screenshot-*.png' -print -quit` ]; then
              mkdir screenshots-$example_name
              mv screenshot-*.png screenshots-$example_name/
            fi
          done
          mkdir traces && mv trace*.json traces/
          mkdir screenshots && mv screenshots-* screenshots/
      - name: save traces
        uses: actions/upload-artifact@v4
        with:
          name: example-traces-linux
          path: traces
      - name: save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-linux
          path: screenshots
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          name: example-run-linux
          path: example-run/
